# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^[a-zA-Z]{1}[a-zA-Z0-9]+$')], verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('token', models.CharField(max_length=32, verbose_name='Token')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Registro usuario temporal',
                'verbose_name_plural': 'Registro usuarios temporales',
            },
        ),
        migrations.CreateModel(
            name='UserEmailUpdate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_email_update', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('new_email', models.EmailField(max_length=254, verbose_name='Nuevo email')),
                ('token', models.CharField(max_length=30, verbose_name='Token')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actualizar email',
                'verbose_name_plural': 'Actualizar emails',
            },
        ),
    ]
