# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_header',
            field=models.ImageField(default='', null=True, upload_to='articles/headers', verbose_name='Imagen cabecera'),
        ),
    ]
