# Generated by Django 2.0rc1 on 2017-11-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171111_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRate',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='article_rate', serialize=False, to='blog.Article', verbose_name='Ratio articulo')),
                ('positives', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
